;;; casual-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual.el

 (autoload 'casual-main-menu "casual" nil t)


;;; Generated autoloads from casual-calc.el

(register-definition-prefixes "casual-calc" '("casual-"))


;;; Generated autoloads from casual-calc-algebra.el

(register-definition-prefixes "casual-calc-algebra" '("casual-"))


;;; Generated autoloads from casual-fileio.el

(register-definition-prefixes "casual-fileio" '("casual-"))


;;; Generated autoloads from casual-financial.el

(register-definition-prefixes "casual-financial" '("casual--fin-"))


;;; Generated autoloads from casual-graphics.el

(register-definition-prefixes "casual-graphics" '("casual--"))


;;; Generated autoloads from casual-labels.el

(register-definition-prefixes "casual-labels" '("casual-"))


;;; Generated autoloads from casual-predicates.el

(register-definition-prefixes "casual-predicates" '("casual-"))


;;; Generated autoloads from casual-random.el

(register-definition-prefixes "casual-random" '("casual--random-interval-0-to-m"))


;;; Generated autoloads from casual-settings.el

(register-definition-prefixes "casual-settings" '("casual-"))


;;; Generated autoloads from casual-stack.el

(register-definition-prefixes "casual-stack" '("casual-"))


;;; Generated autoloads from casual-vector.el

(register-definition-prefixes "casual-vector" '("casual-calc-histogram"))


;;; Generated autoloads from casual-version.el

(register-definition-prefixes "casual-version" '("casual-version"))

;;; End of scraped data

(provide 'casual-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-autoloads.el ends here
