;;; auto-package-update-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from auto-package-update.el

(autoload 'auto-package-update-now "auto-package-update" "\
Update installed Emacs packages.

(fn &optional ASYNC)" t nil)
(autoload 'auto-package-update-now-async "auto-package-update" "\
Update installed Emacs packages with an async manner.
If FORCE is non-nil, kill the update thread anyway.

(fn &optional FORCE)" t nil)
(autoload 'auto-package-update-at-time "auto-package-update" "\
Try to update every day at the specified TIME.

(fn TIME)" nil nil)
(autoload 'auto-package-update-maybe "auto-package-update" "\
Update installed Emacs packages if at least
`auto-package-update-interval' days have passed since the last
update." nil nil)
(register-definition-prefixes "auto-package-update" '("apu--" "auto-package-"))

;;; End of scraped data

(provide 'auto-package-update-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; auto-package-update-autoloads.el ends here
