;;; frecentf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from frecentf.el

(autoload 'frecentf-pick-file "frecentf" "\
Pick a file and call ACTION on it.

When called interactively, call `find-file'

(fn ACTION)" t)
(autoload 'frecentf-pick-dir "frecentf" "\
Pick a file and call ACTION on it.

When called interactively, call `dired'

(fn ACTION)" t)
(defvar frecentf-mode nil "\
Non-nil if Frecentf mode is enabled.
See the `frecentf-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `frecentf-mode'.")
(custom-autoload 'frecentf-mode "frecentf" nil)
(autoload 'frecentf-mode "frecentf" "\
Toggle frecentf mode.

Mostly based off `recentf-mode'

This is a global minor mode.  If called interactively, toggle the
`Frecentf mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='frecentf-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "frecentf" '("frecent"))

;;; End of scraped data

(provide 'frecentf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; frecentf-autoloads.el ends here
